# @package _global_
gpus: 1
use_wandb: False
accelerator: "gpu"
# New arguments for controlling training behavior
train_base: True  # If True, train base GPT-2. If False, fine-tune with adapter.
num_samples: 5
continuation_length: 10  
trainer:
  devices: ${gpus}
  default_root_dir: ${logs_dir}
  accelerator: "gpu"
  num_sanity_val_steps: 0
