# @package _global_

defaults:
  - override /dataset: maze
  - override /model: gpt

model:
  num_hidden_layers: 40
  hidden_size: 128

optim:
  grad_clip: 1
  learning_rate: 0.001
  optimizer: adamw
  schedule_free: False
  warmup_pct: 0.05
  weight_decay: 0.0001
  betas: [0.9, 0.999]

datamodule:
  batch_size: 16
  grid_n: 10
  n_mazes: 100_000
